/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author anton
 */
public class AndraAvdelning extends javax.swing.JFrame {
    
    private InfDB idb;
    private String valdAvdelning;
    private Validering val; 

    /**
     * Creates new form AndraAvdelning
     */
    public AndraAvdelning(InfDB idb) {
        this.idb = idb;
        this.val = new Validering(idb); 
        initComponents();
        populeraValjAvdelning();
        populeraValdStad();
        populeraFalt(); 
        tfAvdid.setEditable(false);
    }
    //Skapar en ArrayList för att hämta namn på de avdlningar som finns i databasen
    public ArrayList hamtaAvdelningNamn(){
        ArrayList<String>avdelningNamnLista = new ArrayList<>(); 
        try{
            avdelningNamnLista = idb.fetchColumn("SELECT namn FROM avdelning"); 
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        return avdelningNamnLista; 
    }
    
    //Metod för att populera de avdelningar som finns i databasen i en combobox
    public void populeraValjAvdelning(){
        ArrayList<String>avdelningNamnLista = hamtaAvdelningNamn(); 
        for(String avdelningLista : avdelningNamnLista){
            cbValjAvdelning.addItem(avdelningLista);
        }
    }
    
    //Skapar en ArrayList för att hämta namn på de städer som finns i databasen
    public ArrayList hamtaStadNamn(){
        ArrayList<String>stadNamnLista = new ArrayList<>();
        try{
            stadNamnLista = idb.fetchColumn("SELECT namn FROM stad"); 
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        return stadNamnLista; 
    }
    
    //Metod för att populera de städer som finns i en combobox
    public void populeraValdStad(){
        ArrayList<String>stadNamnLista = hamtaStadNamn();
        for(String stadLista : stadNamnLista){
            cbStad.addItem(stadLista);
        }
    }
    
    //Populerar de fält som ska finns beronde på vilken avdelning man väljer
    public void populeraFalt(){
        try{
            String id = idb.fetchSingle("SELECT avdid FROM avdelning WHERE namn ='" + valdAvdelning + "'"); 
            String sqlAvdid = idb.fetchSingle("SELECT avdid FROM avdelning WHERE avdid ='" + id + "'");
            String sqlNamn = idb.fetchSingle("SELECT namn FROM avdelning WHERE avdid ='" + id + "'");
            String sqlBeskrivning = idb.fetchSingle("SELECT beskrivning FROM avdelning WHERE avdid ='" + id + "'");
            String sqlAdress = idb.fetchSingle("SELECT adress FROM avdelning WHERE avdid ='" + id + "'");
            String sqlEpost = idb.fetchSingle("SELECT epost FROM avdelning WHERE avdid ='" + id + "'");
            String sqlTele = idb.fetchSingle("SELECT telefon FROM avdelning WHERE avdid ='" + id + "'");
            tfAvdid.setText(sqlAvdid);
            tfNamn.setText(sqlNamn);
            tfBeskrivning.setText(sqlBeskrivning);
            tfAdress.setText(sqlAdress); 
            tfEpost.setText(sqlEpost);
            tfTele.setText(sqlTele);
        }catch(InfException ex){
            System.out.println(ex.getMessage()); 
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValjAvdelning = new javax.swing.JLabel();
        cbValjAvdelning = new javax.swing.JComboBox<>();
        lblAvdid = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        tfAvdid = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTele = new javax.swing.JTextField();
        cbStad = new javax.swing.JComboBox<>();
        btnSpara = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValjAvdelning.setText("Välj avdelning");

        cbValjAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjAvdelningActionPerformed(evt);
            }
        });

        lblAvdid.setText("Avdid");

        lblNamn.setText("Namn");

        lblBeskrivning.setText("Beskrivning");

        lblAdress.setText("Adress");

        lblEpost.setText("Epost");

        lblTele.setText("Telefon");

        lblStad.setText("Stad");

        btnSpara.setText("Spara ändring");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(lblValjAvdelning))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamn)
                                    .addComponent(lblAvdid)
                                    .addComponent(lblBeskrivning)
                                    .addComponent(lblAdress)
                                    .addComponent(lblEpost)
                                    .addComponent(lblTele)
                                    .addComponent(lblStad))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbValjAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAvdid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEpost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnTillbaka))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValjAvdelning)
                    .addComponent(cbValjAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdid)
                    .addComponent(tfAvdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTele)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStad)
                    .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSpara)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbValjAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjAvdelningActionPerformed
        String val = (String) cbValjAvdelning.getSelectedItem();
        valdAvdelning = val; 
        populeraFalt(); 
    }//GEN-LAST:event_cbValjAvdelningActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        if(val.hamtaEpost(tfEpost.getText()) == false){
            JOptionPane.showMessageDialog(this, "Email behöver vara i rätt format, xxxx.x@xxxxx.xxx");
        }else if(val.valideraNumerisk(tfTele.getText()) == false){
            JOptionPane.showMessageDialog(this, "Telefonnummret behöver vara i enbart siffror");
        }else if(val.hamtaEpost(tfEpost.getText()) == true && val.valideraNumerisk(tfTele.getText()) == true){
        try{
            String valdStad = (String) cbStad.getSelectedItem(); 
            String sqlValdStad = idb.fetchSingle("SELECT sid FROM stad WHERE namn ='" + valdStad + "'");
            String id = idb.fetchSingle("SELECT avdid FROM avdelning WHERE namn ='" + valdAvdelning + "'");
            idb.update("UPDATE avdelning SET namn ='" + tfNamn.getText() + "' WHERE avdid =" + id);
            idb.update("UPDATE avdelning SET beskrivning ='" + tfBeskrivning.getText() + "' WHERE avdid =" + id);
            idb.update("UPDATE avdelning SET adress ='" + tfAdress.getText() + "' WHERE avdid =" + id);
            idb.update("UPDATE avdelning SET epost ='" + tfEpost.getText() + "' WHERE avdid =" + id);
            idb.update("UPDATE avdelning SET telefon ='" + tfTele.getText() + "' WHERE avdid =" + id);
            idb.update("UPDATE avdelning SET stad ='" + sqlValdStad + "' WHERE avdid =" + id);
            new Avdelning(idb).setVisible(true);
            this.dispose();
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new Avdelning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbStad;
    private javax.swing.JComboBox<String> cbValjAvdelning;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAvdid;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTele;
    private javax.swing.JLabel lblValjAvdelning;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAvdid;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfTele;
    // End of variables declaration//GEN-END:variables
}
