/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author anton
 */
public class AndraPartner extends javax.swing.JFrame {
    private InfDB idb;
    private String valdPartner;
    private Validering val; 

    /**
     * Creates new form AndraPartner
     */
    public AndraPartner(InfDB idb) {
        this.idb = idb;
        this.val = new Validering(idb); 
        initComponents();
        populeraPartnerNamn();
        populeraStadNamn();
        tfPid.setEditable(false);
        populeraFalt(); 
    }
    
    //Skapar en ArrayList och hämtar alla partner-namn och spar dessa. >Returnera dessa i en lista. 
    public ArrayList hamtaPartnerNamn(){
        ArrayList<String>partnerNamnLista = new ArrayList<>(); 
        try{
            partnerNamnLista = idb.fetchColumn("SELECT namn FROM partner"); 
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        return partnerNamnLista; 
    }
    
    //Metod för att populera Combobox för alla partner-namn. Använder ArrayList partnerNamnLista som skapades ovan för
    // att hjälpa till med detta.
    public void populeraPartnerNamn(){
        ArrayList<String>partnerNamnLista = hamtaPartnerNamn();
        for(String partnerLista : partnerNamnLista){
            cbPartner.addItem(partnerLista);    
        }
    }
    
    //Skapar en ArrayList och hämtar alla namn på städer och spar dessa. Returnera dessa i en lista.
    public ArrayList hamtaStadNamn(){
       ArrayList<String>stadNamnLista = new ArrayList<>();
       try{
           stadNamnLista = idb.fetchColumn("SELECT namn FROM stad"); 
       }catch(InfException ex){
           System.out.println(ex.getMessage());
       }
       return stadNamnLista; 
    }
    
    //Metod för att populera ComboBox för namn på städer. Använder ArrayList stadNamnLista som skapades ovan för 
    // att hjälpa till med detta.
    public void populeraStadNamn(){
        ArrayList<String>stadNamnLista = hamtaStadNamn();
        for(String stadLista : stadNamnLista){
            cbStad.addItem(stadLista);
        }
    }
    
    //Metod för att populera fälten beroende på vilken partner man väljer. 
    public void populeraFalt(){
        try{
        String id = idb.fetchSingle("SELECT pid FROM partner WHERE namn ='" + valdPartner + "'");
        String sqlPid = idb.fetchSingle("SELECT pid FROM partner WHERE pid ='" + id + "'");
        String sqlNamn = idb.fetchSingle("SELECT namn FROM partner WHERE pid ='" + id + "'");
        String sqlKontaktPerson = idb.fetchSingle("SELECT kontaktperson FROM partner WHERE pid ='" + id + "'");
        String sqlKontaktEpost = idb.fetchSingle("SELECT kontaktepost FROM partner WHERE pid ='" + id + "'");
        String sqlTele = idb.fetchSingle("SELECT telefon FROM partner WHERE pid ='" + id + "'");
        String sqlAdress = idb.fetchSingle("SELECT adress FROM partner WHERE pid ='" + id + "'");
        String sqlBranch = idb.fetchSingle("SELECT branch FROM partner WHERE pid ='" + id + "'");
        tfPid.setText(sqlPid);
        tfNamn.setText(sqlNamn);
        tfKontaktPerson.setText(sqlKontaktPerson);
        tfKontaktEpost.setText(sqlKontaktEpost);
        tfTele.setText(sqlTele);
        tfAdress.setText(sqlAdress);
        tfBranch.setText(sqlBranch);
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbaka = new javax.swing.JButton();
        lblValdPartner = new javax.swing.JLabel();
        cbPartner = new javax.swing.JComboBox<>();
        tfAdress = new javax.swing.JTextField();
        lblPid = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblKontaktPerson = new javax.swing.JLabel();
        lblKontaktEpost = new javax.swing.JLabel();
        tfBranch = new javax.swing.JTextField();
        lblTele = new javax.swing.JLabel();
        cbStad = new javax.swing.JComboBox<>();
        lblAdress = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        tfPid = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfKontaktPerson = new javax.swing.JTextField();
        tfKontaktEpost = new javax.swing.JTextField();
        tfTele = new javax.swing.JTextField();
        btnAndra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblValdPartner.setText("Välj partner");

        cbPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPartnerActionPerformed(evt);
            }
        });

        lblPid.setText("Pid");

        lblNamn.setText("Namn");

        lblKontaktPerson.setText("Kontakt person");

        lblKontaktEpost.setText("Kontakt epost");

        lblTele.setText("Telefon");

        lblAdress.setText("Adress");

        lblBranch.setText("Branch");

        lblStad.setText("Stad");

        btnAndra.setText("Spara ändringar");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKontaktPerson)
                    .addComponent(lblPid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKontaktEpost, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTele, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStad, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNamn)
                    .addComponent(tfPid)
                    .addComponent(tfKontaktPerson)
                    .addComponent(tfKontaktEpost)
                    .addComponent(tfTele)
                    .addComponent(tfAdress)
                    .addComponent(tfBranch)
                    .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblValdPartner)
                        .addGap(39, 39, 39)
                        .addComponent(cbPartner, 0, 137, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAndra)))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValdPartner)
                    .addComponent(cbPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPid)
                    .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontaktPerson)
                    .addComponent(tfKontaktPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontaktEpost)
                    .addComponent(tfKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTele, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranch)
                    .addComponent(tfBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStad)
                    .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAndra)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new Partner(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cbPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPartnerActionPerformed
        String val = (String) cbPartner.getSelectedItem();
        valdPartner = val;
        populeraFalt(); 
    }//GEN-LAST:event_cbPartnerActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        if(val.hamtaEpost(tfKontaktEpost.getText()) == false){
            JOptionPane.showMessageDialog(this, "Email behöver vara i rätt format: xxx.x@xxxxx.xxx");
        }else if(val.valideraInternationelltTelefonnummer(tfTele.getText()) == false){
            JOptionPane.showMessageDialog(this, "Telefonnummret behöver vara i rätt format: + följt av 10 siffror "); 
        }else if(val.hamtaEpost(tfKontaktEpost.getText()) == true && val.valideraInternationelltTelefonnummer(tfTele.getText()) == true){
            int taBortRuta = JOptionPane.showConfirmDialog(null, "Är du säker", "meddelande", JOptionPane.YES_NO_OPTION);
            if(taBortRuta == JOptionPane.YES_OPTION){
                try{
                String id = idb.fetchSingle("SELECT pid FROM partner WHERE namn ='" + valdPartner + "'");
                idb.update("UPDATE partner SET namn ='" + tfNamn.getText() + "' WHERE pid = " + id);
                idb.update("UPDATE partner SET kontaktperson ='" + tfKontaktPerson.getText() + "' WHERE pid = " + id);
                idb.update("UPDATE partner SET kontaktepost ='" + tfKontaktEpost.getText() + "' WHERE pid = " + id);
                idb.update("UPDATE partner SET telefon ='" + tfTele.getText() + "' WHERE pid = " + id);
                idb.update("UPDATE partner SET adress ='" + tfAdress.getText() + "' WHERE pid = " + id);
                idb.update("UPDATE partner SET branch ='" + tfBranch.getText() + "' WHERE pid = " + id);
                String valdStad = (String) cbStad.getSelectedItem();
                String dbStad = idb.fetchSingle("SELECT sid FROM stad WHERE namn ='" + valdStad + "'");
                idb.update("UPDATE partner SET stad ='" + dbStad + "' WHERE pid = " + id);
                new Partner(idb).setVisible(true);
                this.dispose();
            }catch(InfException ex){
                System.out.println(ex.getMessage());
            }
        }else{
            new AndraPartner(idb).setVisible(true);
            this.dispose();
        }
        }
    }//GEN-LAST:event_btnAndraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbPartner;
    private javax.swing.JComboBox<String> cbStad;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblKontaktEpost;
    private javax.swing.JLabel lblKontaktPerson;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTele;
    private javax.swing.JLabel lblValdPartner;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBranch;
    private javax.swing.JTextField tfKontaktEpost;
    private javax.swing.JTextField tfKontaktPerson;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPid;
    private javax.swing.JTextField tfTele;
    // End of variables declaration//GEN-END:variables
}
