/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import javax.swing.JOptionPane;
import ngo2024.Services.AnstalldService;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author anton
 */
public class AndraUppgifter extends javax.swing.JFrame {
    private InfDB idb; 
    private String anstalldAid;
    private AnstalldService anstalldService;
    private String inloggadAnvandare;
    private Validering val; 

    /**
     * Creates new form AndraUppgifter
     */
    public AndraUppgifter(InfDB idb, AnstalldService anstalldService, String anstalldAid) {
        this.idb = idb; 
        this.anstalldAid = anstalldAid;
        this.anstalldService = anstalldService;
        this.val = new Validering(idb); 
        initComponents();
        hamtaUppgifter();
        tfAnsDatum.setEditable(false);
        tfAvdelning.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAndraUppgifter = new javax.swing.JLabel();
        lblFnamn = new javax.swing.JLabel();
        lblEnamn = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblAnsDatum = new javax.swing.JLabel();
        lblAvd = new javax.swing.JLabel();
        tfFnamn = new javax.swing.JTextField();
        tfEnamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTele = new javax.swing.JTextField();
        tfAnsDatum = new javax.swing.JTextField();
        tfAvdelning = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAndraUppgifter.setText("Ändra uppgifter");

        lblFnamn.setText("Förnamn");

        lblEnamn.setText("Efternamn");

        lblAdress.setText("Adress");

        lblTele.setText("Telefon");

        lblEpost.setText("Epost");

        lblAnsDatum.setText("Anställningsdatum");

        lblAvd.setText("Avdelning");

        btnSpara.setText("Spara ändring");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFnamn)
                            .addComponent(lblEnamn)
                            .addComponent(lblAdress)
                            .addComponent(lblEpost)
                            .addComponent(lblTele)
                            .addComponent(lblAnsDatum)
                            .addComponent(lblAvd))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfFnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tfEnamn)
                            .addComponent(tfAdress)
                            .addComponent(tfEpost)
                            .addComponent(tfTele)
                            .addComponent(tfAnsDatum)
                            .addComponent(tfAvdelning)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoggaUt)
                        .addGap(64, 64, 64)
                        .addComponent(lblAndraUppgifter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnSpara)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblAndraUppgifter))
                    .addComponent(btnLoggaUt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFnamn)
                    .addComponent(tfFnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnamn)
                    .addComponent(tfEnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTele)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsDatum)
                    .addComponent(tfAnsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvd)
                    .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSpara)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        if(val.hamtaEpost(tfEpost.getText()) == false){
            JOptionPane.showMessageDialog(this, "Epost är skriven i fel format, ange i formatet: xxx.x@xxxxx.xxx");
        }else if(val.valideraAmerikansktTelefonnummer(tfTele.getText()) == false){
            JOptionPane.showMessageDialog(this, "Telefonnumret är skrivet i fel format, ange i formatet: xxx-xxx-xxxx");
        }else if(val.hamtaEpost(tfEpost.getText()) == true && val.valideraAmerikansktTelefonnummer(tfTele.getText()) == true){
        int taBortRuta = JOptionPane.showConfirmDialog(null, "Är du säker, om du sparar ändringar kommer du behöva logga in igen", "meddelande", JOptionPane.YES_NO_OPTION);
        if(taBortRuta == JOptionPane.YES_OPTION){
        anstalldService.uppdateraUppgifter(tfFnamn.getText(), tfEnamn.getText(), tfAdress.getText(),
                tfEpost.getText(), tfTele.getText(), tfAnsDatum.getText(), tfAvdelning.getText());
        new Inloggning(idb).setVisible(true);
        this.dispose();
        }
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        new Inloggning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    //Metod för att hämta de uppgifter man skrivit in i textfälten 
    public void hamtaUppgifter(){
        
        try{
            
             String sqlFnamn = "SELECT fornamn FROM anstalld WHERE aid =" + anstalldAid;
             String sqlEnamn = "SELECT efternamn FROM anstalld WHERE aid =" + anstalldAid;
             String sqlAdress = "SELECT adress FROM anstalld WHERE aid =" + anstalldAid;
             String sqlEpost = "SELECT epost FROM anstalld WHERE aid =" + anstalldAid;
             String sqlTele = "SELECT telefon FROM anstalld WHERE aid =" + anstalldAid;
             String sqlAnsDatum = "SELECT anstallningsdatum FROM anstalld WHERE aid =" + anstalldAid;
             String sqlAvd = "SELECT avdelning FROM anstalld WHERE aid =" + anstalldAid;
             String dbFnamn = idb.fetchSingle(sqlFnamn);
             String dbEnamn = idb.fetchSingle(sqlEnamn);
             String dbAdress = idb.fetchSingle(sqlAdress);
             String dbEpost = idb.fetchSingle(sqlEpost);
             String dbTele = idb.fetchSingle(sqlTele);
             String dbAnsDatum = idb.fetchSingle(sqlAnsDatum);
             String dbAvd = idb.fetchSingle(sqlAvd);
             tfFnamn.setText(dbFnamn);
             tfEnamn.setText(dbEnamn); 
             tfAdress.setText(dbAdress);
             tfEpost.setText(dbEpost); 
             tfTele.setText(dbTele); 
             tfAnsDatum.setText(dbAnsDatum); 
             tfAvdelning.setText(dbAvd); 
        }catch(InfException ettUndantagsFel){
            System.out.println(ettUndantagsFel.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AndraUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAndraUppgifter;
    private javax.swing.JLabel lblAnsDatum;
    private javax.swing.JLabel lblAvd;
    private javax.swing.JLabel lblEnamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFnamn;
    private javax.swing.JLabel lblTele;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAnsDatum;
    private javax.swing.JTextField tfAvdelning;
    private javax.swing.JTextField tfEnamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFnamn;
    private javax.swing.JTextField tfTele;
    // End of variables declaration//GEN-END:variables
}
