package ngo2024;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author tom-l
 */
public class Anstallda extends javax.swing.JFrame {

    
    private InfDB idb;                                  // Ha som standard att ta med dessa 3 fält
    private String inLoggadEPost;
    private String anstalldAid;
    private String avdelningsID; 
    //private int avdelningsID;
    //private int behorighet;
    /**
     * Creates new form Anstallda
     */
    public Anstallda(InfDB idb, String inLoggadEPost, String anstalldAid) 
    {
        initComponents();
        this.idb = idb;
        this.inLoggadEPost = inLoggadEPost;
        this.anstalldAid = anstalldAid; 
        this.setLocationRelativeTo(null);
        setUpLista ();
        hamtaAvdelningsID(); 

    }
    
     public void hamtaAvdelningsID(){
        try{
        String hamtatAvdelningsID = idb.fetchSingle("SELECT avdelning FROM anstalld WHERE aid='" + anstalldAid + "'");
        avdelningsID = hamtatAvdelningsID; 
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
    }

    private void setUpLista() {
        String SQLFraga = "select fornamn, efternamn from ngo_2024.anstalld where avdelning = " + anstalldAid;
        try {
            ArrayList<HashMap<String, String>> lista = idb.fetchRows(SQLFraga);

            for (int i = 0; i < lista.size(); i++) {
                taListaAnstallda.append(lista.get(i).get("fornamn") + " " + lista.get(i).get("efternamn") + "\n");

            }

        } catch (InfException ex) {
            ex.getMessage();

        }

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnstallda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaAnstallda = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();
        btnSokHandlaggarePaMinAvdelning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAnstallda.setText("Anställda på min avdelning");

        taListaAnstallda.setColumns(20);
        taListaAnstallda.setRows(5);
        jScrollPane1.setViewportView(taListaAnstallda);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSokHandlaggarePaMinAvdelning.setText("Sök Handläggare");
        btnSokHandlaggarePaMinAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokHandlaggarePaMinAvdelningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 516, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(300, 300, 300)
                        .addComponent(lblAnstallda))
                    .addComponent(btnSokHandlaggarePaMinAvdelning))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnstallda)
                    .addComponent(btnTillbaka))
                .addGap(18, 18, 18)
                .addComponent(btnSokHandlaggarePaMinAvdelning)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed

        this.setVisible(false);
        new HandlaggareMeny (idb, inLoggadEPost, anstalldAid).setVisible(true);
    
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSokHandlaggarePaMinAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokHandlaggarePaMinAvdelningActionPerformed

        this.setVisible(false);
        new SokHandlaggare (idb, inLoggadEPost, anstalldAid).setVisible(true);


    }//GEN-LAST:event_btnSokHandlaggarePaMinAvdelningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anstallda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anstallda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anstallda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anstallda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    //            new Anstallda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSokHandlaggarePaMinAvdelning;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnstallda;
    private javax.swing.JTextArea taListaAnstallda;
    // End of variables declaration//GEN-END:variables
}
