/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map.Entry;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author anton
 */
public class Avdelning extends javax.swing.JFrame {
    
    private InfDB idb; 

    /**
     * Creates new form Avdelning
     */
    public Avdelning(InfDB idb) {
        this.idb = idb; 
        initComponents();
        populeraValAvdelning();
    }
    
    //Skapar en ArrayList för att hålla alla namn på avdelningar som finns i databasen
    public ArrayList hamtaAvdelningNamn(){
        ArrayList<String>avdelningNamnLista = new ArrayList<>();
        try{
        avdelningNamnLista = idb.fetchColumn("SELECT namn FROM avdelning"); 
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        return avdelningNamnLista; 
    }
    
    //Populerar en combobox med namn på alla avdelningar som finns i databasen
    public void populeraValAvdelning(){
        ArrayList<String>avdelningNamnLista = hamtaAvdelningNamn(); 
        for(String avdelningNamn : avdelningNamnLista){
            cbValAvdelning.addItem(avdelningNamn);
        }
    }
    
    //Skapar en HashMap för att hålla alla uppgifter om en viss avdelning
    public HashMap hamtaAvdelningUppgifter(String namn){
        HashMap<String, String>avdelningUppgifter = new HashMap<>(); 
        try{
            String id = idb.fetchSingle("SELECT avdid FROM avdelning WHERE namn ='" + namn + "'"); 
            avdelningUppgifter = idb.fetchRow("SELECT * FROM avdelning WHERE avdid ='" + id + "'"); 
        }catch(InfException ex){
            System.out.print(ex.getMessage()); 
        }
        return avdelningUppgifter; 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValAvdelning = new javax.swing.JLabel();
        cbValAvdelning = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAvdelningInfo = new javax.swing.JTextArea();
        btnAndraAvdelning = new javax.swing.JButton();
        btnLaggTillAvdelning = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValAvdelning.setText("Välj avdelning");

        cbValAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValAvdelningActionPerformed(evt);
            }
        });

        txAvdelningInfo.setColumns(20);
        txAvdelningInfo.setRows(5);
        jScrollPane1.setViewportView(txAvdelningInfo);

        btnAndraAvdelning.setText("Ändra avdelning");
        btnAndraAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAvdelningActionPerformed(evt);
            }
        });

        btnLaggTillAvdelning.setText("Lägg till avdelning");
        btnLaggTillAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillAvdelningActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addGap(30, 30, 30)
                .addComponent(lblValAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbValAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnAndraAvdelning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLaggTillAvdelning)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValAvdelning)
                            .addComponent(cbValAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnTillbaka))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndraAvdelning)
                    .addComponent(btnLaggTillAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbValAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValAvdelningActionPerformed
        txAvdelningInfo.setText("");
        var val = cbValAvdelning.getSelectedItem(); 
        if(val != null){
            val = (String) val; 
            HashMap<String, String>avdelningUppgifter = hamtaAvdelningUppgifter((String) val); 
            for(Entry<String, String> value : avdelningUppgifter.entrySet()){
                txAvdelningInfo.append(value.getKey() +": " + value.getValue() + ", \n");
            }
        }
    }//GEN-LAST:event_cbValAvdelningActionPerformed

    private void btnAndraAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAvdelningActionPerformed
        new AndraAvdelning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAndraAvdelningActionPerformed

    private void btnLaggTillAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillAvdelningActionPerformed
        new LaggTillAvdelning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLaggTillAvdelningActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminMeny(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Avdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraAvdelning;
    private javax.swing.JButton btnLaggTillAvdelning;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbValAvdelning;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValAvdelning;
    private javax.swing.JTextArea txAvdelningInfo;
    // End of variables declaration//GEN-END:variables
}
