package ngo2024;


import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

   
/**
 *
 * @author tom-l
 */
public class GlobalaMal17 extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String anstalldAid; 

    public GlobalaMal17(InfDB idb, String inloggadAnvandare, String anstalldAid) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.anstalldAid = anstalldAid; 
        setUpInfo();

    }

    // En ArrayList av HashMaps med en 'for loop' som listar upp samtliga mål i ett TextArea
    private void setUpInfo() {
        String SQLFraga = "select hid, namn, malnummer, beskrivning, prioritet from ngo_2024.hallbarhetsmal";
        try {
            ArrayList<HashMap<String, String>> lista = idb.fetchRows(SQLFraga);

            for (int i = 0; i < lista.size(); i++) {
                tfVisningsRuta.append("HållbarhetsID: " + lista.get(i).get("hid") + "\n" + "Namn: " + lista.get(i).get("namn") + "\n" + "Målnummer: "
                        + lista.get(i).get("malnummer") + "\n" + "Beskrivning: " + lista.get(i).get("beskrivning") + "\n" + "Prioritet: "
                        + lista.get(i).get("prioritet") + "\n" + "---------------------------------------- \n");
            }

        } catch (InfException ex) {
            ex.getMessage();

        }
    }

// ----------------------------------------------------------------------------    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGlobalaMal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfVisningsRuta = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGlobalaMal.setText("Globala Mål");

        tfVisningsRuta.setColumns(20);
        tfVisningsRuta.setRows(5);
        jScrollPane1.setViewportView(tfVisningsRuta);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(lblGlobalaMal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(btnTillbaka)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGlobalaMal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTillbaka))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
       
        this.dispose();
        new HandlaggareMeny (idb, inloggadAnvandare, anstalldAid).setVisible(true);
        
        
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
     //           new GlobalaMal17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGlobalaMal;
    private javax.swing.JTextArea tfVisningsRuta;
    // End of variables declaration//GEN-END:variables

}