package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.*;
import javax.swing.*;
import ngo2024.MinaProjekt;
import ngo2024.PartnerVy;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SSIRA
 */
public class HandlaggareMeny extends javax.swing.JFrame {
    
    private InfDB idb;
    private InfException ex;
    private String inloggadAnvandare;
    private String anstalldAid;
    private Validering val; 
    

// KONSTRUKTÖR ---------------------------------------------------
    
    public HandlaggareMeny(InfDB idb, String inloggadAnvandare, String anstalldAid) {
        this.anstalldAid = anstalldAid;
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.val = new Validering(idb); 
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);
        btnProjektChef.setVisible(false);
        hamtaProjektChef();
    }
    
    //Hamtar om inloggad användare är projektchef eller ej 
    public void hamtaProjektChef(){
        if(val.hamtaProjektchef(inloggadAnvandare) == true){
            btnProjektChef.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHandlaggare = new javax.swing.JLabel();
        lblInloggadAnvandare = new javax.swing.JLabel();
        btnPartnersPaProjekt = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnMinaUppgifter = new javax.swing.JButton();
        btnGlobalaMal = new javax.swing.JButton();
        btnVisaProjekt = new javax.swing.JButton();
        btnAnstallda = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        btnProjektSok = new javax.swing.JButton();
        btnProjektChef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHandlaggare.setText("Handläggare");

        lblInloggadAnvandare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInloggadAnvandare.setText("Användare");

        btnPartnersPaProjekt.setText("Visa Partners på Mina Projekt");
        btnPartnersPaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnersPaProjektActionPerformed(evt);
            }
        });

        btnMinaProjekt.setText("Ändra mina projekt");
        btnMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektActionPerformed(evt);
            }
        });

        btnMinaUppgifter.setText("Mina uppgifter");
        btnMinaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaUppgifterActionPerformed(evt);
            }
        });

        btnGlobalaMal.setText("Globala mål");
        btnGlobalaMal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGlobalaMalActionPerformed(evt);
            }
        });

        btnVisaProjekt.setText("Visa projekt");
        btnVisaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaProjektActionPerformed(evt);
            }
        });

        btnAnstallda.setText("Anställda");
        btnAnstallda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnstalldaActionPerformed(evt);
            }
        });

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        btnProjektSok.setText("Sök efter projekt");
        btnProjektSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektSokActionPerformed(evt);
            }
        });

        btnProjektChef.setText("Projektchef");
        btnProjektChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektChefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnLoggaUt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMinaUppgifter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnstallda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGlobalaMal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisaProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPartnersPaProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinaProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProjektSok, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(btnProjektChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinaUppgifter)
                    .addComponent(btnProjektSok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnstallda)
                    .addComponent(btnProjektChef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGlobalaMal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPartnersPaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartnersPaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersPaProjektActionPerformed
        new PartnerVy(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartnersPaProjektActionPerformed

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        new MinaProjekt(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
        new MinaUppgifter(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed

    private void btnGlobalaMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGlobalaMalActionPerformed
        new GlobalaMal17(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGlobalaMalActionPerformed

    private void btnVisaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaProjektActionPerformed
        new ProjektHandlaggare(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVisaProjektActionPerformed

    private void btnAnstalldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnstalldaActionPerformed
        new Anstallda(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnstalldaActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        new Inloggning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnProjektSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektSokActionPerformed
        try{
            String sqlAvdelning = "SELECT avdelning FROM anstalld WHERE aid = " + anstalldAid;
            int avdelning = Integer.parseInt(idb.fetchSingle(sqlAvdelning));
            new ProjektSok(idb, inloggadAnvandare, anstalldAid, avdelning).setVisible(true);
            this.dispose();
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnProjektSokActionPerformed

    private void btnProjektChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektChefActionPerformed
        new ProjektChefMeny(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProjektChefActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandlaggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandlaggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandlaggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandlaggareMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new HandlaggareMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnstallda;
    private javax.swing.JButton btnGlobalaMal;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnPartnersPaProjekt;
    private javax.swing.JButton btnProjektChef;
    private javax.swing.JButton btnProjektSok;
    private javax.swing.JButton btnVisaProjekt;
    private javax.swing.JLabel lblHandlaggare;
    private javax.swing.JLabel lblInloggadAnvandare;
    // End of variables declaration//GEN-END:variables
}
