/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author anton
 */
public class LaggTillPartner extends javax.swing.JFrame {
    private InfDB idb;
    private Validering val; 

    /**
     * Creates new form LaggTillPartner
     */
    public LaggTillPartner(InfDB idb) {
        this.idb = idb; 
        this.val = new Validering(idb); 
        initComponents();
        hamtaPartnerID();
        populeraStadNamn();
        tfPid.setEditable(false);
    }
    
    //Metod för att hämta nästa ID i partner tabellen och lagra det i fältet tfPid. 
    public void hamtaPartnerID(){
        try{
            String nextID = idb.getAutoIncrement("partner", "pid");
            tfPid.setText(nextID);
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    //Skapar en ArrayList och hämtar alla namn på städer och spar dessa. Returnera dessa i en lista.
    public ArrayList hamtaStadNamn(){
       ArrayList<String>stadNamnLista = new ArrayList<>();
       try{
           stadNamnLista = idb.fetchColumn("SELECT namn FROM stad"); 
       }catch(InfException ex){
           System.out.println(ex.getMessage());
       }
       return stadNamnLista; 
    }
    
    //Metod för att populera ComboBox för namn på städer. Använder ArrayList stadNamnLista som skapades ovan för 
    // att hjälpa till med detta.
    public void populeraStadNamn(){
        ArrayList<String>stadNamnLista = hamtaStadNamn();
        for(String stadLista : stadNamnLista){
            cbStad.addItem(stadLista);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTillbaka = new javax.swing.JButton();
        lblPid = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblKontaktPerson = new javax.swing.JLabel();
        lblKontaktEpost = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        tfPid = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfKontaktPerson = new javax.swing.JTextField();
        tfKontaktEpost = new javax.swing.JTextField();
        tfTele = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfBranch = new javax.swing.JTextField();
        cbStad = new javax.swing.JComboBox<>();
        btnLaggTill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTillbaka.setText("Tillbaka");
        lblTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTillbakaActionPerformed(evt);
            }
        });

        lblPid.setText("Pid");

        lblNamn.setText("Namn");

        lblKontaktPerson.setText("Kontakt person");

        lblKontaktEpost.setText("Kontakt epost");

        lblTele.setText("Telefon");

        lblAdress.setText("Adress");

        lblBranch.setText("Branch");

        lblStad.setText("Stad");

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTillbaka)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKontaktPerson)
                    .addComponent(lblPid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKontaktEpost, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTele, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBranch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStad, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKontaktPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnLaggTill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTillbaka)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPid)
                    .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontaktPerson)
                    .addComponent(tfKontaktPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontaktEpost)
                    .addComponent(tfKontaktEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTele, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranch)
                    .addComponent(tfBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStad)
                    .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaggTill)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTillbakaActionPerformed
        new Partner(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblTillbakaActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        if(val.hamtaEpost(tfKontaktEpost.getText()) == false){
            JOptionPane.showMessageDialog(this, "Email behöver vara i rätt format: xxx.x@xxxxx.xxx");
        }else if(val.valideraInternationelltTelefonnummer(tfTele.getText()) == false){
            JOptionPane.showMessageDialog(this, "Telefonnummret behöver vara i rätt format: + följt av 10 siffror "); 
        }else if(val.hamtaEpost(tfKontaktEpost.getText()) == true && val.valideraInternationelltTelefonnummer(tfTele.getText()) == true){
            try{
            int dbID = Integer.parseInt(tfPid.getText()); 
            String dbNamn = tfNamn.getText(); 
            String dbKontaktPerson = tfKontaktPerson.getText();
            String dbKontaktEpost = tfKontaktEpost.getText(); 
            String dbTele = tfTele.getText(); 
            String dbAdress = tfAdress.getText(); 
            String dbBranch = tfBranch.getText();
            String valdStad = (String) cbStad.getSelectedItem(); 
            String dbStad = idb.fetchSingle("SELECT sid FROM stad WHERE namn ='" + valdStad + "'");
            idb.insert("INSERT INTO partner VALUES (" + dbID + ",'" + dbNamn + "','" + dbKontaktPerson + "','" + dbKontaktEpost + "','" + dbTele + "','" + dbAdress + "','" + dbBranch + "','" + dbStad + "')");
            new Partner(idb).setVisible(true);
            this.dispose();
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JComboBox<String> cbStad;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblKontaktEpost;
    private javax.swing.JLabel lblKontaktPerson;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTele;
    private javax.swing.JButton lblTillbaka;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBranch;
    private javax.swing.JTextField tfKontaktEpost;
    private javax.swing.JTextField tfKontaktPerson;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPid;
    private javax.swing.JTextField tfTele;
    // End of variables declaration//GEN-END:variables
}
