/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map.Entry;
import ngo2024.Services.LandService;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author anton
 */
public class LandsUppgifter extends javax.swing.JFrame {

    private InfDB idb;
    private LandService landService; 
    /**
     * Creates new form LandsUppgifter
     */
    public LandsUppgifter(InfDB idb, LandService landService) {
        this.idb = idb;
        this.landService = landService; 
        initComponents();
        populeraValjLand(); 
    }
    
    //Skapar en ArrayList som håller alla namn på länder som finns i databasen
    public ArrayList hamtaLandsNamn(){
        ArrayList<String>landNamnLista = new ArrayList<>(); 
        try{
            landNamnLista = idb.fetchColumn("SELECT namn FROM land"); 
            
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        return landNamnLista;        
    }
    
    //Metod för att populera en combobox med alla namn på länder som finns i databsen 
    public void populeraValjLand(){
        ArrayList<String>landNamnLista = hamtaLandsNamn(); 
        for(String landNamn : landNamnLista){
            cbValjLand.addItem(landNamn);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbValjLand = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txLandUppgifter = new javax.swing.JTextArea();
        btnLaggTillLand = new javax.swing.JButton();
        btnAndraLand = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbValjLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjLandActionPerformed(evt);
            }
        });

        txLandUppgifter.setColumns(20);
        txLandUppgifter.setRows(5);
        jScrollPane1.setViewportView(txLandUppgifter);

        btnLaggTillLand.setText("Lägg till land");
        btnLaggTillLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillLandActionPerformed(evt);
            }
        });

        btnAndraLand.setText("Ändra");
        btnAndraLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLandActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(cbValjLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnLaggTillLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnAndraLand)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addGap(2, 2, 2)
                .addComponent(cbValjLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaggTillLand)
                    .addComponent(btnAndraLand))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbValjLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjLandActionPerformed
        //int val = cbValjLand.getSelectedIndex();
        //jTextArea1.replaceSelection(content);
        txLandUppgifter.setText("");
        var val = cbValjLand.getSelectedItem();
        if(val != null){
            val = (String) val; 
        HashMap<String, String>landsUppgifter = landService.hamtaLandsUppgifter((String) val);
        for(Entry<String, String> value : landsUppgifter.entrySet()){
            txLandUppgifter.append(value.getKey() +": " + value.getValue() + ", \n");
        }
        }
    }//GEN-LAST:event_cbValjLandActionPerformed

    private void btnLaggTillLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillLandActionPerformed

        new LaggTillLand(idb, landService).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnLaggTillLandActionPerformed

    private void btnAndraLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLandActionPerformed
        new AndraLand(idb, landService).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnAndraLandActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminMeny(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandsUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandsUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandsUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandsUppgifter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LandsUppgifter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLand;
    private javax.swing.JButton btnLaggTillLand;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbValjLand;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txLandUppgifter;
    // End of variables declaration//GEN-END:variables
}
