/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SSIRA
 */
public class PartnerVy extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private String anstalldAid;
    private DefaultTableModel tableModel;
    
// KONSTRUKTÖR ---------------------------------------------------
   
   public PartnerVy(InfDB idb, String inloggadAnvandare, String anstalldAid) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.anstalldAid = anstalldAid; 
        this.tableModel = new DefaultTableModel(new Object[]{"Partner ID", "Namn", "Kontaktperson", "Epost", "Telefon", "Address", "Branch", "Stad"}, 0);
        initComponents();
        fetchAndPopulatePartnerTable(); 
        updateTableModel();
        fetchAndPopulatePartnerTable(); 
   
   }
    private void updateTableModel() {
        jTablePartner.setModel(tableModel);
    }
   private void fetchAndPopulatePartnerTable() {
         // Rensa tableModel innan ny data läggs till
    tableModel.setRowCount(0);

    try {
        //Hämta partners endast för projekt där den inloggade användaren är projektchef
        String sqlFraga = "SELECT * FROM partner WHERE pid IN (" +
                          "SELECT partner_pid FROM projekt_partner WHERE pid IN (" +
                          "SELECT pid FROM projekt WHERE projektchef = (" +
                          "SELECT aid FROM anstalld WHERE aid = '" + anstalldAid + "')))";
        
        ArrayList<HashMap<String, String>> partnersPaProjektList = idb.fetchRows(sqlFraga);

        for (HashMap<String, String> partner : partnersPaProjektList) {
            String partnerID = partner.get("pid");
            String namn = partner.get("namn");
            String kontaktperson = partner.get("kontaktperson");
            String epost = partner.get("kontaktepost");
            String telefon = partner.get("telefon");
            String address = partner.get("adress");
            String branch = partner.get("branch");
            String stad = partner.get("stad");
            tableModel.addRow(new Object[]{partnerID, namn, kontaktperson, epost, telefon, address, branch, stad});
        }
    } catch (InfException ex) {
        System.out.println(ex.getMessage());
    }
    }
   
   
   
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePartner = new javax.swing.JScrollPane();
        jTablePartner = new javax.swing.JTable();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Partner ID", "Namn", "Kontaktperson", "Epost", "Telefon", "Address", "Bransch", "Stad"
            }
        ));
        jScrollPanePartner.setViewportView(jTablePartner);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanePartner, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPanePartner, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new HandlaggareMeny(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartnerVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartnerVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartnerVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartnerVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PartnerVy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPanePartner;
    private javax.swing.JTable jTablePartner;
    // End of variables declaration//GEN-END:variables
}
