/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class ProjektSok extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;
    private String anstalldAid;
    private int avdelning;

    public ProjektSok(InfDB idb, String inloggadAnvandare, String anstalldAid, int avdelning) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.anstalldAid = anstalldAid;
        this.avdelning = avdelning; 
        initComponents();
        lblVisaInloggad.setText(inloggadAnvandare);
        hamtaProjekt(); 
        populeraCbStatus();
        updateTable("", "", "Alla"); 
    }
    
    public void populeraCbStatus(){
        jComboBox1.addItem("Pågående");
        jComboBox1.addItem("Avslutat");
        jComboBox1.addItem("Planerat");
    }
    
    private void hamtaProjekt() {
        try {
            String query = "SELECT projekt.pid, projekt.projektnamn, projekt.startdatum, projekt.slutdatum, projekt.status " +
                           "FROM projekt " +
                           "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
                           "JOIN anstalld ON ans_proj.aid =   anstalld.aid "+
                           "WHERE anstalld.avdelning = " + avdelning;
            
            ArrayList<HashMap<String, String>> projektLista = idb.fetchRows(query);
            
            // Skapa en modell för JTable
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Projekt ID");
            model.addColumn("Projektnamn");
            model.addColumn("Startdatum");
            model.addColumn("Slutdatum");
            model.addColumn("Status");
            
            // Lägg till data i modellen
            for (HashMap<String, String> projekt : projektLista) {
                model.addRow(new Object[]{
                    projekt.get("pid"),
                    projekt.get("projektnamn"),
                    projekt.get("startdatum"),
                    projekt.get("slutdatum"),
                    projekt.get("status")
                });
            }
            
            // Sätt modellen för JTable
            jTable1.setModel(model);
            
        } catch (InfException ex) {
            Logger.getLogger(ProjektSok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblFranDatum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtFranDatum = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblInloggad = new javax.swing.JLabel();
        lblVisaInloggad = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setText("Projektsök");

        lblFranDatum.setText("Från Datum");

        jLabel3.setText("Till datum");

        lblStatus.setText("Status");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblInloggad.setText("Inloggad:");

        lblVisaInloggad.setText("jLabel1");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFranDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFranDatum)
                                .addGap(107, 107, 107)
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInloggad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVisaInloggad))
                            .addComponent(btnTillbaka))
                        .addGap(56, 56, 56)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnSok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInloggad)
                            .addComponent(lblVisaInloggad))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFranDatum)
                    .addComponent(jLabel3)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFranDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnSok)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        String franDatum = txtFranDatum.getText();
        String tillDatum = jTextField2.getText();
        String status = (String) jComboBox1.getSelectedItem();
        updateTable(franDatum, tillDatum, status);
    }//GEN-LAST:event_btnSokActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new HandlaggareMeny(idb, inloggadAnvandare, anstalldAid).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    
 
        // ...
    // </editor-fold>                        

    private void updateTable(String franDatum, String tillDatum, String status) {
    try {
        String query = "SELECT projekt.pid, projekt.projektnamn, projekt.startdatum, projekt.slutdatum, projekt.status " +
                       "FROM projekt " +
                       "JOIN ans_proj ON projekt.pid = ans_proj.pid " +
                       "JOIN anstalld ON ans_proj.aid = anstalld.aid " +
                       "WHERE anstalld.avdelning = " + avdelning;

        if (!franDatum.isEmpty()) {
            query += " AND projekt.startdatum >= '" + franDatum + "'";
        }

        if (!tillDatum.isEmpty()) {
            query += " AND projekt.slutdatum <= '" + tillDatum + "'";
        }

        if (!status.equals("Alla")) {
            query += " AND projekt.status = '" + status + "'";
        }

        ArrayList<HashMap<String, String>> projektLista = idb.fetchRows(query);

        // Skapa en modell för JTable
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Projekt ID");
        model.addColumn("Projektnamn");
        model.addColumn("Startdatum");
        model.addColumn("Slutdatum");
        model.addColumn("Status");

        // Lägg till data i modellen
        for (HashMap<String, String> projekt : projektLista) {
            model.addRow(new Object[]{
                projekt.get("pid"),
                projekt.get("projektnamn"),
                projekt.get("startdatum"),
                projekt.get("slutdatum"),
                projekt.get("status")
            });
        }

        // Sätt modellen för JTable
        jTable1.setModel(model);

    } catch (InfException ex) {
        Logger.getLogger(ProjektSok.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    

    
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ProjektSok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ProjektSok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ProjektSok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ProjektSok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
}

    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblFranDatum;
    private javax.swing.JLabel lblInloggad;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblVisaInloggad;
    private javax.swing.JTextField txtFranDatum;
    // End of variables declaration//GEN-END:variables
}
