package ngo2024;


import ngo2024.Anstallda;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tom-l
 */
public class SokHandlaggare extends javax.swing.JFrame {

    
    private InfDB idb;
    private String inLoggadEPost;
    private String anstalldAid;
    
    
    
    
    
    
    public SokHandlaggare(InfDB idb, String inLoggadEPost, String anstalldAid) {
        
        initComponents();
        this.idb = idb;
        this.inLoggadEPost = inLoggadEPost;
        this.anstalldAid = anstalldAid; 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taListaHandlaggare = new javax.swing.JTextArea();
        lblÖvertext = new javax.swing.JLabel();
        tfSokPaNamn = new javax.swing.JTextField();
        tfSokPaEpost = new javax.swing.JTextField();
        lblSokPaFornamn = new javax.swing.JLabel();
        lblSokPaEpost = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taListaHandlaggare.setColumns(20);
        taListaHandlaggare.setRows(5);
        jScrollPane1.setViewportView(taListaHandlaggare);

        lblÖvertext.setText("Handläggare på min avdelning");

        lblSokPaFornamn.setText("Sök på förnamn:");

        lblSokPaEpost.setText("Sök på Epost:");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSokPaFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(lblSokPaEpost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSokPaEpost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSokPaNamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSok)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblÖvertext))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTillbaka))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblÖvertext)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSokPaNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSokPaFornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSokPaEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSokPaEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed

        this.setVisible(false);
        new Anstallda (idb, inLoggadEPost, anstalldAid).setVisible(true);
        
        
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
      //Hämtar förnamn och epost
        String fornamn = tfSokPaNamn.getText();
        String epost = tfSokPaEpost.getText();
        
        //Felmedelande om det inte är korrekt ifyllt
        if (fornamn.isEmpty() && epost.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i minst ett fält");
            
        } else if (epost.isEmpty()) {
            //Sök på förnamn
            String sqlFraga = "select fornamn, efternamn, epost, telefon from anstalld where fornamn = '" + fornamn
                    + "' and avdelning = " + anstalldAid;
            
            taListaHandlaggare.setText("");
            try {
                ArrayList<HashMap<String, String>> lista = idb.fetchRows(sqlFraga);
                
                for (int i = 0; i < lista.size(); i++) {
                    taListaHandlaggare.append(lista.get(i).get("fornamn") + "\n" + lista.get(i).get("efternamn") + "\n"
                            + lista.get(i).get("epost") + "\n" + lista.get(i).get("telefon") + "\n"
                            + "---------------" + "\n");
                }
            } catch (InfException ex) {
                ex.getMessage();
            }        
            // Sök på E-post
        } else if (fornamn.isEmpty()) {
            String sqlFraga = "select fornamn, efternamn, epost, telefon from anstalld where epost = '" + epost
                    + "' and avdelning = " + anstalldAid;
            
            taListaHandlaggare.setText("");
            try {
                ArrayList<HashMap<String, String>> lista = idb.fetchRows(sqlFraga);
                
                for (int i = 0; i < lista.size(); i++) {
                    taListaHandlaggare.append(lista.get(i).get("fornamn") + "\n" + lista.get(i).get("efternamn") + "\n"
                            + lista.get(i).get("epost") + "\n" + lista.get(i).get("telefon") + "\n"
                            + "---------------" + "\n");
                }
            } catch (InfException ex) {
                ex.getMessage();
            }            
            
            //Listar upp information om personen
        } else {
            String sqlFraga = "select fornamn, efternamn, epost, telefon from anstalld where fornamn = '" + fornamn
                    + "' and epost = '" + epost + "' and avdelning = " + anstalldAid;
            
            taListaHandlaggare.setText("");
            try {
                ArrayList<HashMap<String, String>> lista = idb.fetchRows(sqlFraga);
                
                for (int i = 0; i < lista.size(); i++) {
                    taListaHandlaggare.append(lista.get(i).get("fornamn") + "\n" + lista.get(i).get("efternamn") + "\n"
                            + lista.get(i).get("epost") + "\n" + lista.get(i).get("telefon") + "\n"
                            + "---------------" + "\n");
                }
            } catch (InfException ex) {
                ex.getMessage();
            }            



        }
        
        
        
    }//GEN-LAST:event_btnSokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SokHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SokHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SokHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SokHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
      //          new SokHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSokPaEpost;
    private javax.swing.JLabel lblSokPaFornamn;
    private javax.swing.JLabel lblÖvertext;
    private javax.swing.JTextArea taListaHandlaggare;
    private javax.swing.JTextField tfSokPaEpost;
    private javax.swing.JTextField tfSokPaNamn;
    // End of variables declaration//GEN-END:variables
}
