/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author anton
 */
public class TaBortAnstalld extends javax.swing.JFrame {
    
    private InfDB idb;
    private String valdAnstalld; 

    /**
     * Creates new form TaBortAnvandare
     */
    public TaBortAnstalld(InfDB idb) {
        this.idb = idb; 
        initComponents();
        populeraAnstalld(); 
        populeraFalt(); 
    }

    //Skapar en ArrayList för att hämta AnställningsID på alla anställd som finns i databasen
    public ArrayList hamtaAnstalld(){
        ArrayList<String>anstalldLista = new ArrayList<>(); 
        try{
            anstalldLista = idb.fetchColumn("SELECT aid FROM anstalld"); 
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        return anstalldLista; 
    }
    
    //Skapar en metod för att populera combobox med alla AnställningsID som finns i databasen 
    public void populeraAnstalld(){
        cbValdAnstalld.insertItemAt("---", 0);
        ArrayList<String>anstalldLista = hamtaAnstalld(); 
        for(String anstalld : anstalldLista){
            cbValdAnstalld.addItem(anstalld);
        }
    }
    
    //Metod för att populera alla fält utifrån en vald anställd
        public void populeraFalt(){
        try{
            String id = idb.fetchSingle("SELECT aid FROM anstalld where aid ='" + valdAnstalld + "'"); 
            String sqlAid = idb.fetchSingle("SELECT aid FROM anstalld where aid = '" + id + "'"); 
            String sqlFnamn = idb.fetchSingle("SELECT fornamn FROM anstalld where aid = '" + id + "'");
            String sqlEnamn = idb.fetchSingle("SELECT efternamn FROM anstalld where aid = '" + id + "'");
            String sqlAdress = idb.fetchSingle("SELECT adress FROM anstalld where aid = '" + id + "'");
            String sqlEpost = idb.fetchSingle("SELECT epost FROM anstalld where aid = '" + id + "'");
            String sqlTele = idb.fetchSingle("SELECT telefon FROM anstalld where aid = '" + id + "'");
            String sqlAnsDatum = idb.fetchSingle("SELECT anstallningsdatum FROM anstalld where aid = '" + id + "'");
            String sqlAvdelning = idb.fetchSingle("SELECT avdelning FROM anstalld where aid = '" + id + "'");
            tfAid.setText(sqlAid);
            tfFnamn.setText(sqlFnamn);
            tfEnamn.setText(sqlEnamn);
            tfAdress.setText(sqlAdress);
            tfEpost.setText(sqlEpost);
            tfTele.setText(sqlTele); 
            tfAnsDatum.setText(sqlAnsDatum);
            tfAvdelning.setText(sqlAvdelning);
            tfAid.setEditable(false);
            tfFnamn.setEditable(false);
            tfEnamn.setEditable(false);
            tfAdress.setEditable(false);
            tfEpost.setEditable(false);
            tfTele.setEditable(false);
            tfAnsDatum.setEditable(false);
            tfAvdelning.setEditable(false);
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValdAnstalld = new javax.swing.JLabel();
        cbValdAnstalld = new javax.swing.JComboBox<>();
        lblAnsID = new javax.swing.JLabel();
        tfAid = new javax.swing.JTextField();
        lblFnamn = new javax.swing.JLabel();
        tfFnamn = new javax.swing.JTextField();
        lblEnamn = new javax.swing.JLabel();
        tfEnamn = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        lblEpost = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        lblTele = new javax.swing.JLabel();
        tfTele = new javax.swing.JTextField();
        lblAnsDatum = new javax.swing.JLabel();
        tfAnsDatum = new javax.swing.JTextField();
        lblAvdelning = new javax.swing.JLabel();
        tfAvdelning = new javax.swing.JTextField();
        btnTaBort = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValdAnstalld.setText("Välj användare");

        cbValdAnstalld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValdAnstalldActionPerformed(evt);
            }
        });

        lblAnsID.setText("AID");

        lblFnamn.setText("Förnamn");

        lblEnamn.setText("Efternamn");

        lblAdress.setText("Adress");

        lblEpost.setText("Epost");

        lblTele.setText("Telefon");

        lblAnsDatum.setText("Anställningsdatum");

        lblAvdelning.setText("Avdelning");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnsID)
                    .addComponent(lblFnamn)
                    .addComponent(lblEnamn)
                    .addComponent(lblAdress)
                    .addComponent(lblEpost)
                    .addComponent(lblTele)
                    .addComponent(lblAnsDatum)
                    .addComponent(lblAvdelning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addGap(24, 24, 24)
                        .addComponent(lblValdAnstalld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbValdAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnTaBort)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbValdAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValdAnstalld)))
                    .addComponent(btnTillbaka))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsID)
                    .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFnamn)
                    .addComponent(tfFnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnamn)
                    .addComponent(tfEnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTele)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsDatum)
                    .addComponent(tfAnsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTaBort)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbValdAnstalldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValdAnstalldActionPerformed
        String val = (String) cbValdAnstalld.getSelectedItem(); 
        valdAnstalld = val;
        populeraFalt(); 
    }//GEN-LAST:event_cbValdAnstalldActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        int taBortRuta = JOptionPane.showConfirmDialog(null, "Är du säker", "meddelande", JOptionPane.YES_NO_OPTION);
        if(taBortRuta == JOptionPane.YES_OPTION){
        try{
        idb.delete("DELETE FROM admin WHERE aid ='" + valdAnstalld + "'");
        idb.delete("DELETE FROM handlaggare WHERE aid ='" + valdAnstalld + "'");
        idb.delete("DELETE FROM anstalld WHERE aid ='" + valdAnstalld + "'");
        }catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        new AdminMeny(idb).setVisible(true);
        this.dispose();
        }else{
            new TaBortAnstalld(idb).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminMeny(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TaBortAnstalld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbValdAnstalld;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnsDatum;
    private javax.swing.JLabel lblAnsID;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEnamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFnamn;
    private javax.swing.JLabel lblTele;
    private javax.swing.JLabel lblValdAnstalld;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAid;
    private javax.swing.JTextField tfAnsDatum;
    private javax.swing.JTextField tfAvdelning;
    private javax.swing.JTextField tfEnamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFnamn;
    private javax.swing.JTextField tfTele;
    // End of variables declaration//GEN-END:variables
}
